name: projekakhir
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  encrypt: ^5.0.1
  path: ^1.8.0
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  http: ^1.2.1
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - image/Batman.jpg